From ea48505c536de8d97b4a9fa6f0ccf9e46c5d19a2 Mon Sep 17 00:00:00 2001
From: Tomas Mraz <tmraz@fedoraproject.org>
Date: Thu, 4 May 2017 14:43:20 +0200
Subject: [PATCH 2/2] Fix reading of faillockArgs.

---
 authinfo.py | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/authinfo.py b/authinfo.py
index 3bb610fa52bc6486a3da4ec522d7da436f898c82..ffd71a34bc1691ed0f328e6bd07fb9875c8c8214 100644
--- a/authinfo.py
+++ b/authinfo.py
@@ -2158,8 +2158,8 @@ class AuthInfo:
 					self.setParam("enableNullOk", args.find("nullok") >= 0, ref)
 				if module.startswith("pam_faillock"):
 					self.setParam("enableFaillock", True, ref)
-					if args:
-						args.replace('authfail', '').strip()
+					if args and 'authfail' in args:
+						args = args.replace('authfail', '').strip()
 						self.setParam("faillockArgs", args, ref)
 					continue
 			if stack == "account":
-- 
2.9.3

